# Generated by Django 4.0.4 on 2022-06-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majirani', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={},
        ),
    ]
